export const cars = [
  {
    "id": "car-1",
    "name": "Koenigsegg",
    "type": "Hatchback",
    "capacity": 7,
    "fuelTank": 35.2,
    "transmission": "Manual",
    "price": 299,
    "discount": 15,
    "image": "koenigsegg.jpg"
  },
  {
    "id": "car-2",
    "name": "Nissan GT-R",
    "type": "SUV",
    "capacity": 2,
    "fuelTank": 49.9,
    "transmission": "Manual",
    "price": 293,
    "discount": 15,
    "image": "nissan-gtr.jpg"
  },
  {
    "id": "car-3",
    "name": "Rolls-Royce",
    "type": "Hatchback",
    "capacity": 3,
    "fuelTank": 59.8,
    "transmission": "Manual",
    "price": 110,
    "discount": 5,
    "image": "rolls-royce.jpg"
  },
  {
    "id": "car-4",
    "name": "MG ZX Exclusive",
    "type": "Sport",
    "capacity": 3,
    "fuelTank": 46.3,
    "transmission": "Manual",
    "price": 152,
    "discount": 20,
    "image": "mg-zx-exclusive.jpg"
  },
  {
    "id": "car-5",
    "name": "MG ZS",
    "type": "Hatchback",
    "capacity": 5,
    "fuelTank": 65.7,
    "transmission": "Automatic",
    "price": 69,
    "discount": 0,
    "image": "mg-zs.jpg"
  },
  {
    "id": "car-6",
    "name": "MG Hector",
    "type": "Hatchback",
    "capacity": 3,
    "fuelTank": 74.1,
    "transmission": "Manual",
    "price": 132,
    "discount": 10,
    "image": "mg-hector.jpg"
  },
  {
    "id": "car-7",
    "name": "BMW M3",
    "type": "Sport",
    "capacity": 2,
    "fuelTank": 63.0,
    "transmission": "Automatic",
    "price": 250,
    "discount": 10,
    "image": "bmw-m3.jpg"
  },
  {
    "id": "car-8",
    "name": "Mercedes Benz",
    "type": "Hatchback",
    "capacity": 6,
    "fuelTank": 45.7,
    "transmission": "Manual",
    "price": 278,
    "discount": 0,
    "image": "mercedes-benz.jpg"
  },
  {
    "id": "car-9",
    "name": "Porsche Cayenne",
    "type": "Sport",
    "capacity": 8,
    "fuelTank": 35.2,
    "transmission": "Automatic",
    "price": 86,
    "discount": 5,
    "image": "porsche-cayenne.jpg"
  },
  {
    "id": "car-10",
    "name": "Toyota Fortuner",
    "type": "Sedan",
    "capacity": 2,
    "fuelTank": 73.8,
    "transmission": "Automatic",
    "price": 260,
    "discount": 0,
    "image": "toyota-fortuner.jpg"
  },
  {
    "id": "car-11",
    "name": "Honda Accord",
    "type": "Sport",
    "capacity": 8,
    "fuelTank": 50.5,
    "transmission": "Automatic",
    "price": 269,
    "discount": 20,
    "image": "honda-accord.jpg"
  },
  {
    "id": "car-12",
    "name": "Hyundai Creta",
    "type": "Hatchback",
    "capacity": 6,
    "fuelTank": 65.9,
    "transmission": "Automatic",
    "price": 470,
    "discount": 20,
    "image": "hyundai-creta.jpg"
  },
  {
    "id": "car-13",
    "name": "Koenigsegg",
    "type": "Sport",
    "capacity": 7,
    "fuelTank": 59.2,
    "transmission": "Manual",
    "price": 194,
    "discount": 10,
    "image": "koenigsegg.jpg"
  },
  {
    "id": "car-14",
    "name": "Nissan GT-R",
    "type": "Hatchback",
    "capacity": 3,
    "fuelTank": 56.7,
    "transmission": "Manual",
    "price": 374,
    "discount": 20,
    "image": "nissan-gtr.jpg"
  },
  {
    "id": "car-15",
    "name": "Rolls-Royce",
    "type": "SUV",
    "capacity": 3,
    "fuelTank": 43.0,
    "transmission": "Automatic",
    "price": 381,
    "discount": 5,
    "image": "rolls-royce.jpg"
  },
  {
    "id": "car-16",
    "name": "MG ZX Exclusive",
    "type": "Hatchback",
    "capacity": 3,
    "fuelTank": 38.5,
    "transmission": "Automatic",
    "price": 58,
    "discount": 10,
    "image": "mg-zx-exclusive.jpg"
  },
  {
    "id": "car-17",
    "name": "MG ZS",
    "type": "Sedan",
    "capacity": 6,
    "fuelTank": 63.1,
    "transmission": "Automatic",
    "price": 130,
    "discount": 0,
    "image": "mg-zs.jpg"
  },
  {
    "id": "car-18",
    "name": "MG Hector",
    "type": "Sedan",
    "capacity": 3,
    "fuelTank": 38.4,
    "transmission": "Manual",
    "price": 423,
    "discount": 10,
    "image": "mg-hector.jpg"
  },
  {
    "id": "car-19",
    "name": "BMW M3",
    "type": "SUV",
    "capacity": 5,
    "fuelTank": 70.1,
    "transmission": "Manual",
    "price": 97,
    "discount": 15,
    "image": "bmw-m3.jpg"
  },
  {
    "id": "car-20",
    "name": "Mercedes Benz",
    "type": "Sport",
    "capacity": 6,
    "fuelTank": 63.2,
    "transmission": "Automatic",
    "price": 262,
    "discount": 15,
    "image": "mercedes-benz.jpg"
  },
  {
    "id": "car-21",
    "name": "Porsche Cayenne",
    "type": "Sport",
    "capacity": 7,
    "fuelTank": 70.7,
    "transmission": "Manual",
    "price": 458,
    "discount": 15,
    "image": "porsche-cayenne.jpg"
  },
  {
    "id": "car-22",
    "name": "Toyota Fortuner",
    "type": "Hatchback",
    "capacity": 4,
    "fuelTank": 33.5,
    "transmission": "Automatic",
    "price": 191,
    "discount": 0,
    "image": "toyota-fortuner.jpg"
  },
  {
    "id": "car-23",
    "name": "Honda Accord",
    "type": "Sport",
    "capacity": 8,
    "fuelTank": 72.2,
    "transmission": "Manual",
    "price": 288,
    "discount": 20,
    "image": "honda-accord.jpg"
  },
  {
    "id": "car-24",
    "name": "Hyundai Creta",
    "type": "Sport",
    "capacity": 6,
    "fuelTank": 75.0,
    "transmission": "Manual",
    "price": 470,
    "discount": 20,
    "image": "hyundai-creta.jpg"
  },
  {
    "id": "car-25",
    "name": "Koenigsegg",
    "type": "SUV",
    "capacity": 4,
    "fuelTank": 60.8,
    "transmission": "Automatic",
    "price": 427,
    "discount": 10,
    "image": "koenigsegg.jpg"
  },
  {
    "id": "car-26",
    "name": "Nissan GT-R",
    "type": "SUV",
    "capacity": 5,
    "fuelTank": 74.6,
    "transmission": "Manual",
    "price": 94,
    "discount": 10,
    "image": "nissan-gtr.jpg"
  },
  {
    "id": "car-27",
    "name": "Rolls-Royce",
    "type": "Sedan",
    "capacity": 4,
    "fuelTank": 33.5,
    "transmission": "Manual",
    "price": 218,
    "discount": 15,
    "image": "rolls-royce.jpg"
  },
  {
    "id": "car-28",
    "name": "MG ZX Exclusive",
    "type": "Sedan",
    "capacity": 3,
    "fuelTank": 65.0,
    "transmission": "Manual",
    "price": 273,
    "discount": 15,
    "image": "mg-zx-exclusive.jpg"
  },
  {
    "id": "car-29",
    "name": "MG ZS",
    "type": "SUV",
    "capacity": 6,
    "fuelTank": 78.7,
    "transmission": "Manual",
    "price": 409,
    "discount": 15,
    "image": "mg-zs.jpg"
  },
  {
    "id": "car-30",
    "name": "MG Hector",
    "type": "Sedan",
    "capacity": 2,
    "fuelTank": 46.6,
    "transmission": "Manual",
    "price": 300,
    "discount": 10,
    "image": "mg-hector.jpg"
  },
  {
    "id": "car-31",
    "name": "BMW M3",
    "type": "Sedan",
    "capacity": 7,
    "fuelTank": 67.0,
    "transmission": "Manual",
    "price": 233,
    "discount": 5,
    "image": "bmw-m3.jpg"
  },
  {
    "id": "car-32",
    "name": "Mercedes Benz",
    "type": "Sport",
    "capacity": 7,
    "fuelTank": 41.8,
    "transmission": "Automatic",
    "price": 97,
    "discount": 15,
    "image": "mercedes-benz.jpg"
  },
  {
    "id": "car-33",
    "name": "Porsche Cayenne",
    "type": "Sedan",
    "capacity": 4,
    "fuelTank": 67.6,
    "transmission": "Automatic",
    "price": 70,
    "discount": 15,
    "image": "porsche-cayenne.jpg"
  },
  {
    "id": "car-34",
    "name": "Toyota Fortuner",
    "type": "Sedan",
    "capacity": 8,
    "fuelTank": 43.9,
    "transmission": "Automatic",
    "price": 58,
    "discount": 15,
    "image": "toyota-fortuner.jpg"
  },
  {
    "id": "car-35",
    "name": "Honda Accord",
    "type": "SUV",
    "capacity": 7,
    "fuelTank": 40.9,
    "transmission": "Manual",
    "price": 140,
    "discount": 15,
    "image": "honda-accord.jpg"
  },
  {
    "id": "car-36",
    "name": "Hyundai Creta",
    "type": "Sport",
    "capacity": 3,
    "fuelTank": 42.1,
    "transmission": "Automatic",
    "price": 345,
    "discount": 20,
    "image": "hyundai-creta.jpg"
  },
  {
    "id": "car-37",
    "name": "Koenigsegg",
    "type": "SUV",
    "capacity": 3,
    "fuelTank": 74.2,
    "transmission": "Manual",
    "price": 376,
    "discount": 10,
    "image": "koenigsegg.jpg"
  },
  {
    "id": "car-38",
    "name": "Nissan GT-R",
    "type": "Sedan",
    "capacity": 6,
    "fuelTank": 30.9,
    "transmission": "Manual",
    "price": 185,
    "discount": 5,
    "image": "nissan-gtr.jpg"
  },
  {
    "id": "car-39",
    "name": "Rolls-Royce",
    "type": "Sedan",
    "capacity": 6,
    "fuelTank": 45.7,
    "transmission": "Automatic",
    "price": 52,
    "discount": 0,
    "image": "rolls-royce.jpg"
  },
  {
    "id": "car-40",
    "name": "MG ZX Exclusive",
    "type": "SUV",
    "capacity": 8,
    "fuelTank": 64.8,
    "transmission": "Automatic",
    "price": 69,
    "discount": 10,
    "image": "mg-zx-exclusive.jpg"
  },
  {
    "id": "car-41",
    "name": "MG ZS",
    "type": "Sport",
    "capacity": 7,
    "fuelTank": 53.0,
    "transmission": "Automatic",
    "price": 399,
    "discount": 0,
    "image": "mg-zs.jpg"
  },
  {
    "id": "car-42",
    "name": "MG Hector",
    "type": "Hatchback",
    "capacity": 2,
    "fuelTank": 61.2,
    "transmission": "Automatic",
    "price": 54,
    "discount": 10,
    "image": "mg-hector.jpg"
  },
  {
    "id": "car-43",
    "name": "BMW M3",
    "type": "SUV",
    "capacity": 5,
    "fuelTank": 65.5,
    "transmission": "Manual",
    "price": 330,
    "discount": 5,
    "image": "bmw-m3.jpg"
  },
  {
    "id": "car-44",
    "name": "Mercedes Benz",
    "type": "Hatchback",
    "capacity": 7,
    "fuelTank": 47.8,
    "transmission": "Manual",
    "price": 232,
    "discount": 0,
    "image": "mercedes-benz.jpg"
  },
  {
    "id": "car-45",
    "name": "Porsche Cayenne",
    "type": "Sport",
    "capacity": 2,
    "fuelTank": 44.9,
    "transmission": "Automatic",
    "price": 131,
    "discount": 15,
    "image": "porsche-cayenne.jpg"
  },
  {
    "id": "car-46",
    "name": "Toyota Fortuner",
    "type": "Hatchback",
    "capacity": 7,
    "fuelTank": 76.8,
    "transmission": "Manual",
    "price": 304,
    "discount": 10,
    "image": "toyota-fortuner.jpg"
  },
  {
    "id": "car-47",
    "name": "Honda Accord",
    "type": "Sedan",
    "capacity": 3,
    "fuelTank": 79.8,
    "transmission": "Automatic",
    "price": 385,
    "discount": 20,
    "image": "honda-accord.jpg"
  },
  {
    "id": "car-48",
    "name": "Hyundai Creta",
    "type": "Hatchback",
    "capacity": 6,
    "fuelTank": 67.5,
    "transmission": "Manual",
    "price": 139,
    "discount": 0,
    "image": "hyundai-creta.jpg"
  },
  {
    "id": "car-49",
    "name": "Koenigsegg",
    "type": "Hatchback",
    "capacity": 5,
    "fuelTank": 65.6,
    "transmission": "Automatic",
    "price": 397,
    "discount": 15,
    "image": "koenigsegg.jpg"
  },
  {
    "id": "car-50",
    "name": "Nissan GT-R",
    "type": "Sedan",
    "capacity": 7,
    "fuelTank": 78.6,
    "transmission": "Manual",
    "price": 311,
    "discount": 20,
    "image": "nissan-gtr.jpg"
  },
  {
    "id": "car-51",
    "name": "Rolls-Royce",
    "type": "Hatchback",
    "capacity": 4,
    "fuelTank": 31.7,
    "transmission": "Automatic",
    "price": 101,
    "discount": 0,
    "image": "rolls-royce.jpg"
  },
  {
    "id": "car-52",
    "name": "MG ZX Exclusive",
    "type": "Sedan",
    "capacity": 3,
    "fuelTank": 34.4,
    "transmission": "Automatic",
    "price": 114,
    "discount": 5,
    "image": "mg-zx-exclusive.jpg"
  },
  {
    "id": "car-53",
    "name": "MG ZS",
    "type": "Sport",
    "capacity": 2,
    "fuelTank": 70.1,
    "transmission": "Automatic",
    "price": 95,
    "discount": 5,
    "image": "mg-zs.jpg"
  },
  {
    "id": "car-54",
    "name": "MG Hector",
    "type": "SUV",
    "capacity": 8,
    "fuelTank": 51.3,
    "transmission": "Automatic",
    "price": 97,
    "discount": 15,
    "image": "mg-hector.jpg"
  },
  {
    "id": "car-55",
    "name": "BMW M3",
    "type": "Hatchback",
    "capacity": 7,
    "fuelTank": 33.5,
    "transmission": "Automatic",
    "price": 401,
    "discount": 20,
    "image": "bmw-m3.jpg"
  },
  {
    "id": "car-56",
    "name": "Mercedes Benz",
    "type": "Sedan",
    "capacity": 7,
    "fuelTank": 31.9,
    "transmission": "Automatic",
    "price": 160,
    "discount": 15,
    "image": "mercedes-benz.jpg"
  },
  {
    "id": "car-57",
    "name": "Porsche Cayenne",
    "type": "SUV",
    "capacity": 6,
    "fuelTank": 31.8,
    "transmission": "Automatic",
    "price": 213,
    "discount": 5,
    "image": "porsche-cayenne.jpg"
  },
  {
    "id": "car-58",
    "name": "Toyota Fortuner",
    "type": "Hatchback",
    "capacity": 3,
    "fuelTank": 71.2,
    "transmission": "Manual",
    "price": 292,
    "discount": 5,
    "image": "toyota-fortuner.jpg"
  },
  {
    "id": "car-59",
    "name": "Honda Accord",
    "type": "SUV",
    "capacity": 8,
    "fuelTank": 75.9,
    "transmission": "Manual",
    "price": 104,
    "discount": 20,
    "image": "honda-accord.jpg"
  },
  {
    "id": "car-60",
    "name": "Hyundai Creta",
    "type": "SUV",
    "capacity": 6,
    "fuelTank": 35.7,
    "transmission": "Automatic",
    "price": 401,
    "discount": 5,
    "image": "hyundai-creta.jpg"
  },
  {
    "id": "car-61",
    "name": "Koenigsegg",
    "type": "Sedan",
    "capacity": 5,
    "fuelTank": 73.3,
    "transmission": "Automatic",
    "price": 454,
    "discount": 0,
    "image": "koenigsegg.jpg"
  },
  {
    "id": "car-62",
    "name": "Nissan GT-R",
    "type": "Hatchback",
    "capacity": 2,
    "fuelTank": 59.2,
    "transmission": "Automatic",
    "price": 283,
    "discount": 10,
    "image": "nissan-gtr.jpg"
  },
  {
    "id": "car-63",
    "name": "Rolls-Royce",
    "type": "Sport",
    "capacity": 6,
    "fuelTank": 44.0,
    "transmission": "Automatic",
    "price": 378,
    "discount": 20,
    "image": "rolls-royce.jpg"
  },
  {
    "id": "car-64",
    "name": "MG ZX Exclusive",
    "type": "Sport",
    "capacity": 6,
    "fuelTank": 38.9,
    "transmission": "Manual",
    "price": 451,
    "discount": 10,
    "image": "mg-zx-exclusive.jpg"
  },
  {
    "id": "car-65",
    "name": "MG ZS",
    "type": "Hatchback",
    "capacity": 6,
    "fuelTank": 40.0,
    "transmission": "Manual",
    "price": 472,
    "discount": 15,
    "image": "mg-zs.jpg"
  },
  {
    "id": "car-66",
    "name": "MG Hector",
    "type": "Hatchback",
    "capacity": 7,
    "fuelTank": 73.8,
    "transmission": "Automatic",
    "price": 345,
    "discount": 20,
    "image": "mg-hector.jpg"
  },
  {
    "id": "car-67",
    "name": "BMW M3",
    "type": "Sport",
    "capacity": 2,
    "fuelTank": 57.5,
    "transmission": "Manual",
    "price": 420,
    "discount": 0,
    "image": "bmw-m3.jpg"
  },
  {
    "id": "car-68",
    "name": "Mercedes Benz",
    "type": "Sport",
    "capacity": 4,
    "fuelTank": 32.2,
    "transmission": "Manual",
    "price": 348,
    "discount": 20,
    "image": "mercedes-benz.jpg"
  },
  {
    "id": "car-69",
    "name": "Porsche Cayenne",
    "type": "Hatchback",
    "capacity": 2,
    "fuelTank": 41.1,
    "transmission": "Automatic",
    "price": 283,
    "discount": 5,
    "image": "porsche-cayenne.jpg"
  },
  {
    "id": "car-70",
    "name": "Toyota Fortuner",
    "type": "Sedan",
    "capacity": 8,
    "fuelTank": 47.1,
    "transmission": "Automatic",
    "price": 304,
    "discount": 15,
    "image": "toyota-fortuner.jpg"
  },
  {
    "id": "car-71",
    "name": "Honda Accord",
    "type": "SUV",
    "capacity": 4,
    "fuelTank": 71.8,
    "transmission": "Automatic",
    "price": 179,
    "discount": 15,
    "image": "honda-accord.jpg"
  },
  {
    "id": "car-72",
    "name": "Hyundai Creta",
    "type": "SUV",
    "capacity": 4,
    "fuelTank": 70.5,
    "transmission": "Automatic",
    "price": 227,
    "discount": 10,
    "image": "hyundai-creta.jpg"
  },
  {
    "id": "car-73",
    "name": "Koenigsegg",
    "type": "SUV",
    "capacity": 6,
    "fuelTank": 43.5,
    "transmission": "Manual",
    "price": 291,
    "discount": 10,
    "image": "koenigsegg.jpg"
  },
  {
    "id": "car-74",
    "name": "Nissan GT-R",
    "type": "Hatchback",
    "capacity": 3,
    "fuelTank": 57.7,
    "transmission": "Manual",
    "price": 168,
    "discount": 0,
    "image": "nissan-gtr.jpg"
  },
  {
    "id": "car-75",
    "name": "Rolls-Royce",
    "type": "Sedan",
    "capacity": 5,
    "fuelTank": 50.7,
    "transmission": "Automatic",
    "price": 111,
    "discount": 5,
    "image": "rolls-royce.jpg"
  },
  {
    "id": "car-76",
    "name": "MG ZX Exclusive",
    "type": "SUV",
    "capacity": 7,
    "fuelTank": 75.5,
    "transmission": "Manual",
    "price": 277,
    "discount": 5,
    "image": "mg-zx-exclusive.jpg"
  },
  {
    "id": "car-77",
    "name": "MG ZS",
    "type": "SUV",
    "capacity": 6,
    "fuelTank": 42.6,
    "transmission": "Automatic",
    "price": 389,
    "discount": 0,
    "image": "mg-zs.jpg"
  },
  {
    "id": "car-78",
    "name": "MG Hector",
    "type": "SUV",
    "capacity": 3,
    "fuelTank": 54.1,
    "transmission": "Manual",
    "price": 225,
    "discount": 15,
    "image": "mg-hector.jpg"
  },
  {
    "id": "car-79",
    "name": "BMW M3",
    "type": "Hatchback",
    "capacity": 8,
    "fuelTank": 40.3,
    "transmission": "Automatic",
    "price": 361,
    "discount": 10,
    "image": "bmw-m3.jpg"
  },
  {
    "id": "car-80",
    "name": "Mercedes Benz",
    "type": "Sedan",
    "capacity": 5,
    "fuelTank": 77.4,
    "transmission": "Manual",
    "price": 471,
    "discount": 20,
    "image": "mercedes-benz.jpg"
  },
  {
    "id": "car-81",
    "name": "Porsche Cayenne",
    "type": "Hatchback",
    "capacity": 6,
    "fuelTank": 45.1,
    "transmission": "Automatic",
    "price": 275,
    "discount": 10,
    "image": "porsche-cayenne.jpg"
  },
  {
    "id": "car-82",
    "name": "Toyota Fortuner",
    "type": "SUV",
    "capacity": 7,
    "fuelTank": 60.5,
    "transmission": "Manual",
    "price": 312,
    "discount": 20,
    "image": "toyota-fortuner.jpg"
  },
  {
    "id": "car-83",
    "name": "Honda Accord",
    "type": "Sport",
    "capacity": 8,
    "fuelTank": 43.9,
    "transmission": "Manual",
    "price": 160,
    "discount": 15,
    "image": "honda-accord.jpg"
  },
  {
    "id": "car-84",
    "name": "Hyundai Creta",
    "type": "Sedan",
    "capacity": 8,
    "fuelTank": 65.0,
    "transmission": "Automatic",
    "price": 319,
    "discount": 10,
    "image": "hyundai-creta.jpg"
  },
  {
    "id": "car-85",
    "name": "Koenigsegg",
    "type": "Hatchback",
    "capacity": 6,
    "fuelTank": 53.0,
    "transmission": "Manual",
    "price": 173,
    "discount": 0,
    "image": "koenigsegg.jpg"
  },
  {
    "id": "car-86",
    "name": "Nissan GT-R",
    "type": "SUV",
    "capacity": 4,
    "fuelTank": 48.2,
    "transmission": "Manual",
    "price": 490,
    "discount": 15,
    "image": "nissan-gtr.jpg"
  },
  {
    "id": "car-87",
    "name": "Rolls-Royce",
    "type": "Sedan",
    "capacity": 7,
    "fuelTank": 30.4,
    "transmission": "Manual",
    "price": 261,
    "discount": 10,
    "image": "rolls-royce.jpg"
  },
  {
    "id": "car-88",
    "name": "MG ZX Exclusive",
    "type": "Hatchback",
    "capacity": 5,
    "fuelTank": 65.6,
    "transmission": "Manual",
    "price": 397,
    "discount": 5,
    "image": "mg-zx-exclusive.jpg"
  },
  {
    "id": "car-89",
    "name": "MG ZS",
    "type": "SUV",
    "capacity": 5,
    "fuelTank": 50.4,
    "transmission": "Manual",
    "price": 281,
    "discount": 5,
    "image": "mg-zs.jpg"
  },
  {
    "id": "car-90",
    "name": "MG Hector",
    "type": "SUV",
    "capacity": 8,
    "fuelTank": 37.7,
    "transmission": "Manual",
    "price": 159,
    "discount": 5,
    "image": "mg-hector.jpg"
  },
  {
    "id": "car-91",
    "name": "BMW M3",
    "type": "Sedan",
    "capacity": 4,
    "fuelTank": 51.2,
    "transmission": "Automatic",
    "price": 206,
    "discount": 20,
    "image": "bmw-m3.jpg"
  },
  {
    "id": "car-92",
    "name": "Mercedes Benz",
    "type": "Sedan",
    "capacity": 4,
    "fuelTank": 73.8,
    "transmission": "Automatic",
    "price": 342,
    "discount": 15,
    "image": "mercedes-benz.jpg"
  },
  {
    "id": "car-93",
    "name": "Porsche Cayenne",
    "type": "Sedan",
    "capacity": 2,
    "fuelTank": 62.9,
    "transmission": "Manual",
    "price": 236,
    "discount": 10,
    "image": "porsche-cayenne.jpg"
  },
  {
    "id": "car-94",
    "name": "Toyota Fortuner",
    "type": "Hatchback",
    "capacity": 6,
    "fuelTank": 41.1,
    "transmission": "Automatic",
    "price": 474,
    "discount": 20,
    "image": "toyota-fortuner.jpg"
  },
  {
    "id": "car-95",
    "name": "Honda Accord",
    "type": "Sedan",
    "capacity": 7,
    "fuelTank": 40.5,
    "transmission": "Automatic",
    "price": 445,
    "discount": 5,
    "image": "honda-accord.jpg"
  },
  {
    "id": "car-96",
    "name": "Hyundai Creta",
    "type": "Hatchback",
    "capacity": 4,
    "fuelTank": 78.5,
    "transmission": "Automatic",
    "price": 280,
    "discount": 5,
    "image": "hyundai-creta.jpg"
  },
  {
    "id": "car-97",
    "name": "Koenigsegg",
    "type": "Sport",
    "capacity": 5,
    "fuelTank": 77.8,
    "transmission": "Manual",
    "price": 168,
    "discount": 20,
    "image": "koenigsegg.jpg"
  },
  {
    "id": "car-98",
    "name": "Nissan GT-R",
    "type": "Sedan",
    "capacity": 7,
    "fuelTank": 30.1,
    "transmission": "Manual",
    "price": 157,
    "discount": 10,
    "image": "nissan-gtr.jpg"
  },
  {
    "id": "car-99",
    "name": "Rolls-Royce",
    "type": "Sedan",
    "capacity": 2,
    "fuelTank": 66.6,
    "transmission": "Manual",
    "price": 227,
    "discount": 0,
    "image": "rolls-royce.jpg"
  },
  {
    "id": "car-100",
    "name": "MG ZX Exclusive",
    "type": "Sport",
    "capacity": 4,
    "fuelTank": 50.5,
    "transmission": "Automatic",
    "price": 127,
    "discount": 15,
    "image": "mg-zx-exclusive.jpg"
  },
  {
    "id": "car-101",
    "name": "MG ZS",
    "type": "SUV",
    "capacity": 7,
    "fuelTank": 72.4,
    "transmission": "Automatic",
    "price": 437,
    "discount": 0,
    "image": "mg-zs.jpg"
  },
  {
    "id": "car-102",
    "name": "MG Hector",
    "type": "Hatchback",
    "capacity": 8,
    "fuelTank": 70.4,
    "transmission": "Manual",
    "price": 458,
    "discount": 20,
    "image": "mg-hector.jpg"
  },
  {
    "id": "car-103",
    "name": "BMW M3",
    "type": "SUV",
    "capacity": 6,
    "fuelTank": 41.3,
    "transmission": "Automatic",
    "price": 238,
    "discount": 5,
    "image": "bmw-m3.jpg"
  },
  {
    "id": "car-104",
    "name": "Mercedes Benz",
    "type": "Sedan",
    "capacity": 8,
    "fuelTank": 39.7,
    "transmission": "Manual",
    "price": 387,
    "discount": 15,
    "image": "mercedes-benz.jpg"
  },
  {
    "id": "car-105",
    "name": "Porsche Cayenne",
    "type": "Sport",
    "capacity": 2,
    "fuelTank": 78.5,
    "transmission": "Automatic",
    "price": 320,
    "discount": 10,
    "image": "porsche-cayenne.jpg"
  },
  {
    "id": "car-106",
    "name": "Toyota Fortuner",
    "type": "Sedan",
    "capacity": 4,
    "fuelTank": 31.8,
    "transmission": "Automatic",
    "price": 285,
    "discount": 5,
    "image": "toyota-fortuner.jpg"
  },
  {
    "id": "car-107",
    "name": "Honda Accord",
    "type": "Sport",
    "capacity": 2,
    "fuelTank": 54.2,
    "transmission": "Automatic",
    "price": 137,
    "discount": 10,
    "image": "honda-accord.jpg"
  },
  {
    "id": "car-108",
    "name": "Hyundai Creta",
    "type": "Sport",
    "capacity": 7,
    "fuelTank": 44.2,
    "transmission": "Manual",
    "price": 353,
    "discount": 20,
    "image": "hyundai-creta.jpg"
  },
  {
    "id": "car-109",
    "name": "Koenigsegg",
    "type": "Hatchback",
    "capacity": 5,
    "fuelTank": 30.7,
    "transmission": "Automatic",
    "price": 206,
    "discount": 0,
    "image": "koenigsegg.jpg"
  },
  {
    "id": "car-110",
    "name": "Nissan GT-R",
    "type": "Sport",
    "capacity": 3,
    "fuelTank": 36.0,
    "transmission": "Automatic",
    "price": 225,
    "discount": 10,
    "image": "nissan-gtr.jpg"
  },
  {
    "id": "car-111",
    "name": "Rolls-Royce",
    "type": "Hatchback",
    "capacity": 8,
    "fuelTank": 40.9,
    "transmission": "Manual",
    "price": 209,
    "discount": 10,
    "image": "rolls-royce.jpg"
  },
  {
    "id": "car-112",
    "name": "MG ZX Exclusive",
    "type": "Sedan",
    "capacity": 3,
    "fuelTank": 42.6,
    "transmission": "Manual",
    "price": 228,
    "discount": 20,
    "image": "mg-zx-exclusive.jpg"
  },
  {
    "id": "car-113",
    "name": "MG ZS",
    "type": "Hatchback",
    "capacity": 8,
    "fuelTank": 47.5,
    "transmission": "Manual",
    "price": 356,
    "discount": 5,
    "image": "mg-zs.jpg"
  },
  {
    "id": "car-114",
    "name": "MG Hector",
    "type": "Sedan",
    "capacity": 8,
    "fuelTank": 39.6,
    "transmission": "Manual",
    "price": 162,
    "discount": 10,
    "image": "mg-hector.jpg"
  },
  {
    "id": "car-115",
    "name": "BMW M3",
    "type": "Hatchback",
    "capacity": 8,
    "fuelTank": 65.2,
    "transmission": "Manual",
    "price": 205,
    "discount": 15,
    "image": "bmw-m3.jpg"
  },
  {
    "id": "car-116",
    "name": "Mercedes Benz",
    "type": "Sedan",
    "capacity": 4,
    "fuelTank": 51.0,
    "transmission": "Automatic",
    "price": 421,
    "discount": 15,
    "image": "mercedes-benz.jpg"
  },
  {
    "id": "car-117",
    "name": "Porsche Cayenne",
    "type": "Hatchback",
    "capacity": 2,
    "fuelTank": 56.9,
    "transmission": "Automatic",
    "price": 118,
    "discount": 0,
    "image": "porsche-cayenne.jpg"
  },
  {
    "id": "car-118",
    "name": "Toyota Fortuner",
    "type": "Hatchback",
    "capacity": 2,
    "fuelTank": 75.6,
    "transmission": "Manual",
    "price": 440,
    "discount": 0,
    "image": "toyota-fortuner.jpg"
  },
  {
    "id": "car-119",
    "name": "Honda Accord",
    "type": "Sport",
    "capacity": 4,
    "fuelTank": 53.9,
    "transmission": "Manual",
    "price": 397,
    "discount": 0,
    "image": "honda-accord.jpg"
  },
  {
    "id": "car-120",
    "name": "Hyundai Creta",
    "type": "Sedan",
    "capacity": 2,
    "fuelTank": 42.5,
    "transmission": "Automatic",
    "price": 165,
    "discount": 0,
    "image": "hyundai-creta.jpg"
  },
  {
    "id": "car-121",
    "name": "Koenigsegg",
    "type": "Sedan",
    "capacity": 7,
    "fuelTank": 71.2,
    "transmission": "Manual",
    "price": 445,
    "discount": 20,
    "image": "koenigsegg.jpg"
  },
  {
    "id": "car-122",
    "name": "Nissan GT-R",
    "type": "Sport",
    "capacity": 4,
    "fuelTank": 51.8,
    "transmission": "Manual",
    "price": 331,
    "discount": 15,
    "image": "nissan-gtr.jpg"
  },
  {
    "id": "car-123",
    "name": "Rolls-Royce",
    "type": "Hatchback",
    "capacity": 6,
    "fuelTank": 72.9,
    "transmission": "Automatic",
    "price": 406,
    "discount": 10,
    "image": "rolls-royce.jpg"
  },
  {
    "id": "car-124",
    "name": "MG ZX Exclusive",
    "type": "Hatchback",
    "capacity": 7,
    "fuelTank": 33.2,
    "transmission": "Automatic",
    "price": 117,
    "discount": 5,
    "image": "mg-zx-exclusive.jpg"
  },
  {
    "id": "car-125",
    "name": "MG ZS",
    "type": "Hatchback",
    "capacity": 3,
    "fuelTank": 57.9,
    "transmission": "Manual",
    "price": 137,
    "discount": 5,
    "image": "mg-zs.jpg"
  },
  {
    "id": "car-126",
    "name": "MG Hector",
    "type": "Sport",
    "capacity": 3,
    "fuelTank": 43.1,
    "transmission": "Manual",
    "price": 243,
    "discount": 10,
    "image": "mg-hector.jpg"
  },
  {
    "id": "car-127",
    "name": "BMW M3",
    "type": "SUV",
    "capacity": 4,
    "fuelTank": 72.6,
    "transmission": "Automatic",
    "price": 334,
    "discount": 15,
    "image": "bmw-m3.jpg"
  },
  {
    "id": "car-128",
    "name": "Mercedes Benz",
    "type": "Sedan",
    "capacity": 2,
    "fuelTank": 40.7,
    "transmission": "Automatic",
    "price": 483,
    "discount": 10,
    "image": "mercedes-benz.jpg"
  },
  {
    "id": "car-129",
    "name": "Porsche Cayenne",
    "type": "SUV",
    "capacity": 7,
    "fuelTank": 68.4,
    "transmission": "Automatic",
    "price": 204,
    "discount": 10,
    "image": "porsche-cayenne.jpg"
  },
  {
    "id": "car-130",
    "name": "Toyota Fortuner",
    "type": "Hatchback",
    "capacity": 3,
    "fuelTank": 35.9,
    "transmission": "Manual",
    "price": 460,
    "discount": 0,
    "image": "toyota-fortuner.jpg"
  },
  {
    "id": "car-131",
    "name": "Honda Accord",
    "type": "Sedan",
    "capacity": 2,
    "fuelTank": 53.9,
    "transmission": "Manual",
    "price": 66,
    "discount": 5,
    "image": "honda-accord.jpg"
  },
  {
    "id": "car-132",
    "name": "Hyundai Creta",
    "type": "Sport",
    "capacity": 2,
    "fuelTank": 30.5,
    "transmission": "Automatic",
    "price": 282,
    "discount": 10,
    "image": "hyundai-creta.jpg"
  },
  {
    "id": "car-133",
    "name": "Koenigsegg",
    "type": "Hatchback",
    "capacity": 5,
    "fuelTank": 69.4,
    "transmission": "Manual",
    "price": 85,
    "discount": 5,
    "image": "koenigsegg.jpg"
  },
  {
    "id": "car-134",
    "name": "Nissan GT-R",
    "type": "Hatchback",
    "capacity": 3,
    "fuelTank": 62.9,
    "transmission": "Manual",
    "price": 289,
    "discount": 0,
    "image": "nissan-gtr.jpg"
  },
  {
    "id": "car-135",
    "name": "Rolls-Royce",
    "type": "Sedan",
    "capacity": 8,
    "fuelTank": 55.7,
    "transmission": "Automatic",
    "price": 93,
    "discount": 0,
    "image": "rolls-royce.jpg"
  },
  {
    "id": "car-136",
    "name": "MG ZX Exclusive",
    "type": "SUV",
    "capacity": 6,
    "fuelTank": 39.4,
    "transmission": "Automatic",
    "price": 445,
    "discount": 5,
    "image": "mg-zx-exclusive.jpg"
  },
  {
    "id": "car-137",
    "name": "MG ZS",
    "type": "Sedan",
    "capacity": 8,
    "fuelTank": 47.0,
    "transmission": "Automatic",
    "price": 120,
    "discount": 15,
    "image": "mg-zs.jpg"
  },
  {
    "id": "car-138",
    "name": "MG Hector",
    "type": "Sport",
    "capacity": 5,
    "fuelTank": 68.4,
    "transmission": "Manual",
    "price": 470,
    "discount": 15,
    "image": "mg-hector.jpg"
  },
  {
    "id": "car-139",
    "name": "BMW M3",
    "type": "Sedan",
    "capacity": 5,
    "fuelTank": 41.4,
    "transmission": "Automatic",
    "price": 222,
    "discount": 10,
    "image": "bmw-m3.jpg"
  },
  {
    "id": "car-140",
    "name": "Mercedes Benz",
    "type": "Sedan",
    "capacity": 6,
    "fuelTank": 79.4,
    "transmission": "Manual",
    "price": 356,
    "discount": 5,
    "image": "mercedes-benz.jpg"
  },
  {
    "id": "car-141",
    "name": "Porsche Cayenne",
    "type": "Sedan",
    "capacity": 7,
    "fuelTank": 55.8,
    "transmission": "Manual",
    "price": 254,
    "discount": 15,
    "image": "porsche-cayenne.jpg"
  },
  {
    "id": "car-142",
    "name": "Toyota Fortuner",
    "type": "Hatchback",
    "capacity": 3,
    "fuelTank": 77.1,
    "transmission": "Manual",
    "price": 130,
    "discount": 10,
    "image": "toyota-fortuner.jpg"
  },
  {
    "id": "car-143",
    "name": "Honda Accord",
    "type": "Sport",
    "capacity": 4,
    "fuelTank": 72.4,
    "transmission": "Manual",
    "price": 90,
    "discount": 15,
    "image": "honda-accord.jpg"
  },
  {
    "id": "car-144",
    "name": "Hyundai Creta",
    "type": "Sport",
    "capacity": 7,
    "fuelTank": 38.1,
    "transmission": "Automatic",
    "price": 490,
    "discount": 5,
    "image": "hyundai-creta.jpg"
  },
  {
    "id": "car-145",
    "name": "Koenigsegg",
    "type": "Hatchback",
    "capacity": 2,
    "fuelTank": 36.1,
    "transmission": "Automatic",
    "price": 395,
    "discount": 10,
    "image": "koenigsegg.jpg"
  },
  {
    "id": "car-146",
    "name": "Nissan GT-R",
    "type": "Hatchback",
    "capacity": 7,
    "fuelTank": 79.0,
    "transmission": "Manual",
    "price": 405,
    "discount": 20,
    "image": "nissan-gtr.jpg"
  },
  {
    "id": "car-147",
    "name": "Rolls-Royce",
    "type": "Sedan",
    "capacity": 7,
    "fuelTank": 41.5,
    "transmission": "Automatic",
    "price": 137,
    "discount": 0,
    "image": "rolls-royce.jpg"
  },
  {
    "id": "car-148",
    "name": "MG ZX Exclusive",
    "type": "SUV",
    "capacity": 3,
    "fuelTank": 46.5,
    "transmission": "Automatic",
    "price": 178,
    "discount": 0,
    "image": "mg-zx-exclusive.jpg"
  },
  {
    "id": "car-149",
    "name": "MG ZS",
    "type": "SUV",
    "capacity": 5,
    "fuelTank": 35.5,
    "transmission": "Automatic",
    "price": 336,
    "discount": 15,
    "image": "mg-zs.jpg"
  },
  {
    "id": "car-150",
    "name": "MG Hector",
    "type": "Hatchback",
    "capacity": 3,
    "fuelTank": 37.7,
    "transmission": "Automatic",
    "price": 403,
    "discount": 20,
    "image": "mg-hector.jpg"
  },
  {
    "id": "car-151",
    "name": "BMW M3",
    "type": "Hatchback",
    "capacity": 5,
    "fuelTank": 36.8,
    "transmission": "Manual",
    "price": 410,
    "discount": 15,
    "image": "bmw-m3.jpg"
  },
  {
    "id": "car-152",
    "name": "Mercedes Benz",
    "type": "Sedan",
    "capacity": 4,
    "fuelTank": 79.8,
    "transmission": "Manual",
    "price": 82,
    "discount": 20,
    "image": "mercedes-benz.jpg"
  },
  {
    "id": "car-153",
    "name": "Porsche Cayenne",
    "type": "Sport",
    "capacity": 2,
    "fuelTank": 55.0,
    "transmission": "Automatic",
    "price": 92,
    "discount": 0,
    "image": "porsche-cayenne.jpg"
  },
  {
    "id": "car-154",
    "name": "Toyota Fortuner",
    "type": "Hatchback",
    "capacity": 5,
    "fuelTank": 46.2,
    "transmission": "Manual",
    "price": 392,
    "discount": 5,
    "image": "toyota-fortuner.jpg"
  },
  {
    "id": "car-155",
    "name": "Honda Accord",
    "type": "Sport",
    "capacity": 6,
    "fuelTank": 65.7,
    "transmission": "Automatic",
    "price": 73,
    "discount": 15,
    "image": "honda-accord.jpg"
  },
  {
    "id": "car-156",
    "name": "Hyundai Creta",
    "type": "Sport",
    "capacity": 3,
    "fuelTank": 44.6,
    "transmission": "Automatic",
    "price": 169,
    "discount": 5,
    "image": "hyundai-creta.jpg"
  },
  {
    "id": "car-157",
    "name": "Koenigsegg",
    "type": "Sport",
    "capacity": 3,
    "fuelTank": 34.3,
    "transmission": "Manual",
    "price": 236,
    "discount": 10,
    "image": "koenigsegg.jpg"
  },
  {
    "id": "car-158",
    "name": "Nissan GT-R",
    "type": "SUV",
    "capacity": 8,
    "fuelTank": 71.5,
    "transmission": "Automatic",
    "price": 318,
    "discount": 5,
    "image": "nissan-gtr.jpg"
  },
  {
    "id": "car-159",
    "name": "Rolls-Royce",
    "type": "Sport",
    "capacity": 8,
    "fuelTank": 75.7,
    "transmission": "Automatic",
    "price": 322,
    "discount": 5,
    "image": "rolls-royce.jpg"
  },
  {
    "id": "car-160",
    "name": "MG ZX Exclusive",
    "type": "Hatchback",
    "capacity": 2,
    "fuelTank": 76.3,
    "transmission": "Manual",
    "price": 422,
    "discount": 20,
    "image": "mg-zx-exclusive.jpg"
  },
  {
    "id": "car-161",
    "name": "MG ZS",
    "type": "SUV",
    "capacity": 3,
    "fuelTank": 49.2,
    "transmission": "Automatic",
    "price": 385,
    "discount": 5,
    "image": "mg-zs.jpg"
  },
  {
    "id": "car-162",
    "name": "MG Hector",
    "type": "Sport",
    "capacity": 8,
    "fuelTank": 46.0,
    "transmission": "Manual",
    "price": 436,
    "discount": 20,
    "image": "mg-hector.jpg"
  },
  {
    "id": "car-163",
    "name": "BMW M3",
    "type": "SUV",
    "capacity": 3,
    "fuelTank": 46.0,
    "transmission": "Automatic",
    "price": 136,
    "discount": 20,
    "image": "bmw-m3.jpg"
  },
  {
    "id": "car-164",
    "name": "Mercedes Benz",
    "type": "SUV",
    "capacity": 4,
    "fuelTank": 48.6,
    "transmission": "Automatic",
    "price": 221,
    "discount": 0,
    "image": "mercedes-benz.jpg"
  },
  {
    "id": "car-165",
    "name": "Porsche Cayenne",
    "type": "Sedan",
    "capacity": 7,
    "fuelTank": 55.5,
    "transmission": "Automatic",
    "price": 162,
    "discount": 0,
    "image": "porsche-cayenne.jpg"
  },
  {
    "id": "car-166",
    "name": "Toyota Fortuner",
    "type": "Hatchback",
    "capacity": 5,
    "fuelTank": 75.7,
    "transmission": "Manual",
    "price": 363,
    "discount": 5,
    "image": "toyota-fortuner.jpg"
  },
  {
    "id": "car-167",
    "name": "Honda Accord",
    "type": "Sedan",
    "capacity": 7,
    "fuelTank": 39.0,
    "transmission": "Automatic",
    "price": 187,
    "discount": 20,
    "image": "honda-accord.jpg"
  },
  {
    "id": "car-168",
    "name": "Hyundai Creta",
    "type": "Sport",
    "capacity": 7,
    "fuelTank": 46.5,
    "transmission": "Automatic",
    "price": 178,
    "discount": 10,
    "image": "hyundai-creta.jpg"
  },
  {
    "id": "car-169",
    "name": "Koenigsegg",
    "type": "SUV",
    "capacity": 3,
    "fuelTank": 56.8,
    "transmission": "Manual",
    "price": 213,
    "discount": 5,
    "image": "koenigsegg.jpg"
  },
  {
    "id": "car-170",
    "name": "Nissan GT-R",
    "type": "SUV",
    "capacity": 6,
    "fuelTank": 57.1,
    "transmission": "Automatic",
    "price": 206,
    "discount": 10,
    "image": "nissan-gtr.jpg"
  },
  {
    "id": "car-171",
    "name": "Rolls-Royce",
    "type": "Sport",
    "capacity": 3,
    "fuelTank": 41.2,
    "transmission": "Automatic",
    "price": 453,
    "discount": 20,
    "image": "rolls-royce.jpg"
  },
  {
    "id": "car-172",
    "name": "MG ZX Exclusive",
    "type": "Sport",
    "capacity": 6,
    "fuelTank": 66.1,
    "transmission": "Manual",
    "price": 131,
    "discount": 5,
    "image": "mg-zx-exclusive.jpg"
  },
  {
    "id": "car-173",
    "name": "MG ZS",
    "type": "Sport",
    "capacity": 8,
    "fuelTank": 47.4,
    "transmission": "Manual",
    "price": 302,
    "discount": 15,
    "image": "mg-zs.jpg"
  },
  {
    "id": "car-174",
    "name": "MG Hector",
    "type": "SUV",
    "capacity": 3,
    "fuelTank": 61.6,
    "transmission": "Manual",
    "price": 117,
    "discount": 10,
    "image": "mg-hector.jpg"
  },
  {
    "id": "car-175",
    "name": "BMW M3",
    "type": "Sedan",
    "capacity": 7,
    "fuelTank": 55.8,
    "transmission": "Manual",
    "price": 52,
    "discount": 0,
    "image": "bmw-m3.jpg"
  },
  {
    "id": "car-176",
    "name": "Mercedes Benz",
    "type": "Sport",
    "capacity": 6,
    "fuelTank": 79.1,
    "transmission": "Automatic",
    "price": 93,
    "discount": 10,
    "image": "mercedes-benz.jpg"
  },
  {
    "id": "car-177",
    "name": "Porsche Cayenne",
    "type": "Sedan",
    "capacity": 5,
    "fuelTank": 61.8,
    "transmission": "Manual",
    "price": 209,
    "discount": 20,
    "image": "porsche-cayenne.jpg"
  },
  {
    "id": "car-178",
    "name": "Toyota Fortuner",
    "type": "Hatchback",
    "capacity": 5,
    "fuelTank": 35.0,
    "transmission": "Automatic",
    "price": 416,
    "discount": 0,
    "image": "toyota-fortuner.jpg"
  },
  {
    "id": "car-179",
    "name": "Honda Accord",
    "type": "Sport",
    "capacity": 3,
    "fuelTank": 36.5,
    "transmission": "Manual",
    "price": 357,
    "discount": 15,
    "image": "honda-accord.jpg"
  },
  {
    "id": "car-180",
    "name": "Hyundai Creta",
    "type": "Hatchback",
    "capacity": 7,
    "fuelTank": 55.2,
    "transmission": "Automatic",
    "price": 201,
    "discount": 15,
    "image": "hyundai-creta.jpg"
  },
  {
    "id": "car-181",
    "name": "Koenigsegg",
    "type": "Sedan",
    "capacity": 8,
    "fuelTank": 62.1,
    "transmission": "Automatic",
    "price": 244,
    "discount": 5,
    "image": "koenigsegg.jpg"
  },
  {
    "id": "car-182",
    "name": "Nissan GT-R",
    "type": "Sport",
    "capacity": 7,
    "fuelTank": 31.9,
    "transmission": "Manual",
    "price": 311,
    "discount": 15,
    "image": "nissan-gtr.jpg"
  },
  {
    "id": "car-183",
    "name": "Rolls-Royce",
    "type": "Sport",
    "capacity": 5,
    "fuelTank": 68.5,
    "transmission": "Automatic",
    "price": 325,
    "discount": 5,
    "image": "rolls-royce.jpg"
  },
  {
    "id": "car-184",
    "name": "MG ZX Exclusive",
    "type": "Sport",
    "capacity": 2,
    "fuelTank": 38.2,
    "transmission": "Manual",
    "price": 256,
    "discount": 20,
    "image": "mg-zx-exclusive.jpg"
  },
  {
    "id": "car-185",
    "name": "MG ZS",
    "type": "Sport",
    "capacity": 4,
    "fuelTank": 70.0,
    "transmission": "Automatic",
    "price": 313,
    "discount": 15,
    "image": "mg-zs.jpg"
  },
  {
    "id": "car-186",
    "name": "MG Hector",
    "type": "Hatchback",
    "capacity": 8,
    "fuelTank": 30.7,
    "transmission": "Manual",
    "price": 451,
    "discount": 20,
    "image": "mg-hector.jpg"
  },
  {
    "id": "car-187",
    "name": "BMW M3",
    "type": "Hatchback",
    "capacity": 5,
    "fuelTank": 77.6,
    "transmission": "Automatic",
    "price": 199,
    "discount": 10,
    "image": "bmw-m3.jpg"
  },
  {
    "id": "car-188",
    "name": "Mercedes Benz",
    "type": "SUV",
    "capacity": 7,
    "fuelTank": 50.2,
    "transmission": "Manual",
    "price": 322,
    "discount": 20,
    "image": "mercedes-benz.jpg"
  },
  {
    "id": "car-189",
    "name": "Porsche Cayenne",
    "type": "Sport",
    "capacity": 7,
    "fuelTank": 70.9,
    "transmission": "Automatic",
    "price": 328,
    "discount": 5,
    "image": "porsche-cayenne.jpg"
  },
  {
    "id": "car-190",
    "name": "Toyota Fortuner",
    "type": "Hatchback",
    "capacity": 4,
    "fuelTank": 60.5,
    "transmission": "Manual",
    "price": 439,
    "discount": 15,
    "image": "toyota-fortuner.jpg"
  },
  {
    "id": "car-191",
    "name": "Honda Accord",
    "type": "Hatchback",
    "capacity": 4,
    "fuelTank": 32.7,
    "transmission": "Automatic",
    "price": 162,
    "discount": 10,
    "image": "honda-accord.jpg"
  },
  {
    "id": "car-192",
    "name": "Hyundai Creta",
    "type": "Hatchback",
    "capacity": 2,
    "fuelTank": 47.4,
    "transmission": "Manual",
    "price": 145,
    "discount": 10,
    "image": "hyundai-creta.jpg"
  },
  {
    "id": "car-193",
    "name": "Koenigsegg",
    "type": "Hatchback",
    "capacity": 8,
    "fuelTank": 53.8,
    "transmission": "Automatic",
    "price": 347,
    "discount": 15,
    "image": "koenigsegg.jpg"
  },
  {
    "id": "car-194",
    "name": "Nissan GT-R",
    "type": "SUV",
    "capacity": 2,
    "fuelTank": 61.4,
    "transmission": "Manual",
    "price": 180,
    "discount": 5,
    "image": "nissan-gtr.jpg"
  },
  {
    "id": "car-195",
    "name": "Rolls-Royce",
    "type": "SUV",
    "capacity": 3,
    "fuelTank": 57.7,
    "transmission": "Manual",
    "price": 494,
    "discount": 15,
    "image": "rolls-royce.jpg"
  },
  {
    "id": "car-196",
    "name": "MG ZX Exclusive",
    "type": "Hatchback",
    "capacity": 4,
    "fuelTank": 60.7,
    "transmission": "Manual",
    "price": 387,
    "discount": 5,
    "image": "mg-zx-exclusive.jpg"
  },
  {
    "id": "car-197",
    "name": "MG ZS",
    "type": "Hatchback",
    "capacity": 8,
    "fuelTank": 49.9,
    "transmission": "Manual",
    "price": 324,
    "discount": 0,
    "image": "mg-zs.jpg"
  },
  {
    "id": "car-198",
    "name": "MG Hector",
    "type": "Sedan",
    "capacity": 7,
    "fuelTank": 35.1,
    "transmission": "Automatic",
    "price": 385,
    "discount": 10,
    "image": "mg-hector.jpg"
  },
  {
    "id": "car-199",
    "name": "BMW M3",
    "type": "Sedan",
    "capacity": 6,
    "fuelTank": 61.0,
    "transmission": "Automatic",
    "price": 72,
    "discount": 20,
    "image": "bmw-m3.jpg"
  },
  {
    "id": "car-200",
    "name": "Mercedes Benz",
    "type": "Hatchback",
    "capacity": 6,
    "fuelTank": 52.2,
    "transmission": "Manual",
    "price": 249,
    "discount": 20,
    "image": "mercedes-benz.jpg"
  },
  {
    "id": "car-201",
    "name": "Porsche Cayenne",
    "type": "Sedan",
    "capacity": 7,
    "fuelTank": 68.5,
    "transmission": "Automatic",
    "price": 244,
    "discount": 10,
    "image": "porsche-cayenne.jpg"
  },
  {
    "id": "car-202",
    "name": "Toyota Fortuner",
    "type": "SUV",
    "capacity": 6,
    "fuelTank": 57.7,
    "transmission": "Manual",
    "price": 351,
    "discount": 15,
    "image": "toyota-fortuner.jpg"
  },
  {
    "id": "car-203",
    "name": "Honda Accord",
    "type": "Sedan",
    "capacity": 2,
    "fuelTank": 36.4,
    "transmission": "Automatic",
    "price": 335,
    "discount": 20,
    "image": "honda-accord.jpg"
  },
  {
    "id": "car-204",
    "name": "Hyundai Creta",
    "type": "Sedan",
    "capacity": 8,
    "fuelTank": 51.3,
    "transmission": "Automatic",
    "price": 339,
    "discount": 0,
    "image": "hyundai-creta.jpg"
  },
  {
    "id": "car-205",
    "name": "Koenigsegg",
    "type": "SUV",
    "capacity": 2,
    "fuelTank": 61.9,
    "transmission": "Manual",
    "price": 493,
    "discount": 20,
    "image": "koenigsegg.jpg"
  },
  {
    "id": "car-206",
    "name": "Nissan GT-R",
    "type": "Hatchback",
    "capacity": 6,
    "fuelTank": 37.7,
    "transmission": "Automatic",
    "price": 263,
    "discount": 5,
    "image": "nissan-gtr.jpg"
  },
  {
    "id": "car-207",
    "name": "Rolls-Royce",
    "type": "SUV",
    "capacity": 3,
    "fuelTank": 43.7,
    "transmission": "Automatic",
    "price": 281,
    "discount": 0,
    "image": "rolls-royce.jpg"
  },
  {
    "id": "car-208",
    "name": "MG ZX Exclusive",
    "type": "Sport",
    "capacity": 8,
    "fuelTank": 60.0,
    "transmission": "Automatic",
    "price": 325,
    "discount": 10,
    "image": "mg-zx-exclusive.jpg"
  },
  {
    "id": "car-209",
    "name": "MG ZS",
    "type": "SUV",
    "capacity": 8,
    "fuelTank": 47.5,
    "transmission": "Manual",
    "price": 227,
    "discount": 0,
    "image": "mg-zs.jpg"
  },
  {
    "id": "car-210",
    "name": "MG Hector",
    "type": "Sedan",
    "capacity": 7,
    "fuelTank": 79.0,
    "transmission": "Manual",
    "price": 80,
    "discount": 10,
    "image": "mg-hector.jpg"
  },
  {
    "id": "car-211",
    "name": "BMW M3",
    "type": "SUV",
    "capacity": 4,
    "fuelTank": 33.0,
    "transmission": "Automatic",
    "price": 436,
    "discount": 0,
    "image": "bmw-m3.jpg"
  },
  {
    "id": "car-212",
    "name": "Mercedes Benz",
    "type": "Sedan",
    "capacity": 3,
    "fuelTank": 33.1,
    "transmission": "Manual",
    "price": 457,
    "discount": 0,
    "image": "mercedes-benz.jpg"
  },
  {
    "id": "car-213",
    "name": "Porsche Cayenne",
    "type": "Hatchback",
    "capacity": 3,
    "fuelTank": 33.9,
    "transmission": "Automatic",
    "price": 490,
    "discount": 20,
    "image": "porsche-cayenne.jpg"
  },
  {
    "id": "car-214",
    "name": "Toyota Fortuner",
    "type": "Sedan",
    "capacity": 7,
    "fuelTank": 41.1,
    "transmission": "Automatic",
    "price": 472,
    "discount": 15,
    "image": "toyota-fortuner.jpg"
  },
  {
    "id": "car-215",
    "name": "Honda Accord",
    "type": "Hatchback",
    "capacity": 6,
    "fuelTank": 30.7,
    "transmission": "Automatic",
    "price": 460,
    "discount": 20,
    "image": "honda-accord.jpg"
  },
  {
    "id": "car-216",
    "name": "Hyundai Creta",
    "type": "Sport",
    "capacity": 2,
    "fuelTank": 46.6,
    "transmission": "Automatic",
    "price": 212,
    "discount": 20,
    "image": "hyundai-creta.jpg"
  },
  {
    "id": "car-217",
    "name": "Koenigsegg",
    "type": "Sport",
    "capacity": 7,
    "fuelTank": 43.3,
    "transmission": "Automatic",
    "price": 310,
    "discount": 5,
    "image": "koenigsegg.jpg"
  },
  {
    "id": "car-218",
    "name": "Nissan GT-R",
    "type": "Hatchback",
    "capacity": 6,
    "fuelTank": 62.2,
    "transmission": "Automatic",
    "price": 65,
    "discount": 5,
    "image": "nissan-gtr.jpg"
  },
  {
    "id": "car-219",
    "name": "Rolls-Royce",
    "type": "Sport",
    "capacity": 5,
    "fuelTank": 75.9,
    "transmission": "Automatic",
    "price": 404,
    "discount": 5,
    "image": "rolls-royce.jpg"
  },
  {
    "id": "car-220",
    "name": "MG ZX Exclusive",
    "type": "SUV",
    "capacity": 7,
    "fuelTank": 33.7,
    "transmission": "Automatic",
    "price": 429,
    "discount": 0,
    "image": "mg-zx-exclusive.jpg"
  },
  {
    "id": "car-221",
    "name": "MG ZS",
    "type": "Sport",
    "capacity": 7,
    "fuelTank": 70.2,
    "transmission": "Manual",
    "price": 104,
    "discount": 15,
    "image": "mg-zs.jpg"
  },
  {
    "id": "car-222",
    "name": "MG Hector",
    "type": "Sedan",
    "capacity": 6,
    "fuelTank": 53.0,
    "transmission": "Manual",
    "price": 242,
    "discount": 5,
    "image": "mg-hector.jpg"
  },
  {
    "id": "car-223",
    "name": "BMW M3",
    "type": "Sport",
    "capacity": 7,
    "fuelTank": 43.3,
    "transmission": "Manual",
    "price": 65,
    "discount": 20,
    "image": "bmw-m3.jpg"
  },
  {
    "id": "car-224",
    "name": "Mercedes Benz",
    "type": "Hatchback",
    "capacity": 5,
    "fuelTank": 60.9,
    "transmission": "Automatic",
    "price": 127,
    "discount": 20,
    "image": "mercedes-benz.jpg"
  },
  {
    "id": "car-225",
    "name": "Porsche Cayenne",
    "type": "SUV",
    "capacity": 2,
    "fuelTank": 67.7,
    "transmission": "Manual",
    "price": 352,
    "discount": 15,
    "image": "porsche-cayenne.jpg"
  },
  {
    "id": "car-226",
    "name": "Toyota Fortuner",
    "type": "Sport",
    "capacity": 8,
    "fuelTank": 61.9,
    "transmission": "Manual",
    "price": 251,
    "discount": 10,
    "image": "toyota-fortuner.jpg"
  },
  {
    "id": "car-227",
    "name": "Honda Accord",
    "type": "Hatchback",
    "capacity": 6,
    "fuelTank": 32.7,
    "transmission": "Automatic",
    "price": 285,
    "discount": 10,
    "image": "honda-accord.jpg"
  },
  {
    "id": "car-228",
    "name": "Hyundai Creta",
    "type": "SUV",
    "capacity": 4,
    "fuelTank": 71.8,
    "transmission": "Automatic",
    "price": 207,
    "discount": 20,
    "image": "hyundai-creta.jpg"
  },
  {
    "id": "car-229",
    "name": "Koenigsegg",
    "type": "Sport",
    "capacity": 2,
    "fuelTank": 34.9,
    "transmission": "Automatic",
    "price": 120,
    "discount": 20,
    "image": "koenigsegg.jpg"
  },
  {
    "id": "car-230",
    "name": "Nissan GT-R",
    "type": "Hatchback",
    "capacity": 2,
    "fuelTank": 51.2,
    "transmission": "Manual",
    "price": 358,
    "discount": 20,
    "image": "nissan-gtr.jpg"
  },
  {
    "id": "car-231",
    "name": "Rolls-Royce",
    "type": "Hatchback",
    "capacity": 5,
    "fuelTank": 37.5,
    "transmission": "Manual",
    "price": 51,
    "discount": 5,
    "image": "rolls-royce.jpg"
  },
  {
    "id": "car-232",
    "name": "MG ZX Exclusive",
    "type": "Sport",
    "capacity": 3,
    "fuelTank": 48.3,
    "transmission": "Manual",
    "price": 253,
    "discount": 10,
    "image": "mg-zx-exclusive.jpg"
  },
  {
    "id": "car-233",
    "name": "MG ZS",
    "type": "Sedan",
    "capacity": 8,
    "fuelTank": 45.9,
    "transmission": "Automatic",
    "price": 60,
    "discount": 10,
    "image": "mg-zs.jpg"
  },
  {
    "id": "car-234",
    "name": "MG Hector",
    "type": "Hatchback",
    "capacity": 7,
    "fuelTank": 63.7,
    "transmission": "Manual",
    "price": 56,
    "discount": 20,
    "image": "mg-hector.jpg"
  },
  {
    "id": "car-235",
    "name": "BMW M3",
    "type": "SUV",
    "capacity": 4,
    "fuelTank": 74.4,
    "transmission": "Automatic",
    "price": 489,
    "discount": 20,
    "image": "bmw-m3.jpg"
  },
  {
    "id": "car-236",
    "name": "Mercedes Benz",
    "type": "SUV",
    "capacity": 4,
    "fuelTank": 65.4,
    "transmission": "Manual",
    "price": 106,
    "discount": 15,
    "image": "mercedes-benz.jpg"
  },
  {
    "id": "car-237",
    "name": "Porsche Cayenne",
    "type": "Sedan",
    "capacity": 7,
    "fuelTank": 73.6,
    "transmission": "Manual",
    "price": 426,
    "discount": 10,
    "image": "porsche-cayenne.jpg"
  },
  {
    "id": "car-238",
    "name": "Toyota Fortuner",
    "type": "Sedan",
    "capacity": 2,
    "fuelTank": 45.7,
    "transmission": "Automatic",
    "price": 223,
    "discount": 15,
    "image": "toyota-fortuner.jpg"
  },
  {
    "id": "car-239",
    "name": "Honda Accord",
    "type": "Hatchback",
    "capacity": 6,
    "fuelTank": 47.2,
    "transmission": "Manual",
    "price": 460,
    "discount": 15,
    "image": "honda-accord.jpg"
  },
  {
    "id": "car-240",
    "name": "Hyundai Creta",
    "type": "Sedan",
    "capacity": 6,
    "fuelTank": 76.9,
    "transmission": "Automatic",
    "price": 243,
    "discount": 15,
    "image": "hyundai-creta.jpg"
  },
  {
    "id": "car-241",
    "name": "Koenigsegg",
    "type": "Sport",
    "capacity": 7,
    "fuelTank": 51.3,
    "transmission": "Manual",
    "price": 435,
    "discount": 15,
    "image": "koenigsegg.jpg"
  },
  {
    "id": "car-242",
    "name": "Nissan GT-R",
    "type": "Sport",
    "capacity": 4,
    "fuelTank": 59.1,
    "transmission": "Manual",
    "price": 117,
    "discount": 5,
    "image": "nissan-gtr.jpg"
  },
  {
    "id": "car-243",
    "name": "Rolls-Royce",
    "type": "Hatchback",
    "capacity": 4,
    "fuelTank": 62.5,
    "transmission": "Automatic",
    "price": 81,
    "discount": 10,
    "image": "rolls-royce.jpg"
  },
  {
    "id": "car-244",
    "name": "MG ZX Exclusive",
    "type": "SUV",
    "capacity": 5,
    "fuelTank": 47.9,
    "transmission": "Automatic",
    "price": 372,
    "discount": 0,
    "image": "mg-zx-exclusive.jpg"
  },
  {
    "id": "car-245",
    "name": "MG ZS",
    "type": "Sport",
    "capacity": 2,
    "fuelTank": 35.7,
    "transmission": "Automatic",
    "price": 250,
    "discount": 15,
    "image": "mg-zs.jpg"
  },
  {
    "id": "car-246",
    "name": "MG Hector",
    "type": "Hatchback",
    "capacity": 3,
    "fuelTank": 47.8,
    "transmission": "Manual",
    "price": 218,
    "discount": 0,
    "image": "mg-hector.jpg"
  },
  {
    "id": "car-247",
    "name": "BMW M3",
    "type": "Hatchback",
    "capacity": 2,
    "fuelTank": 63.3,
    "transmission": "Automatic",
    "price": 475,
    "discount": 0,
    "image": "bmw-m3.jpg"
  },
  {
    "id": "car-248",
    "name": "Mercedes Benz",
    "type": "Sedan",
    "capacity": 6,
    "fuelTank": 71.2,
    "transmission": "Manual",
    "price": 119,
    "discount": 10,
    "image": "mercedes-benz.jpg"
  },
  {
    "id": "car-249",
    "name": "Porsche Cayenne",
    "type": "Sport",
    "capacity": 5,
    "fuelTank": 43.8,
    "transmission": "Manual",
    "price": 455,
    "discount": 20,
    "image": "porsche-cayenne.jpg"
  },
  {
    "id": "car-250",
    "name": "Toyota Fortuner",
    "type": "SUV",
    "capacity": 7,
    "fuelTank": 74.2,
    "transmission": "Manual",
    "price": 270,
    "discount": 15,
    "image": "toyota-fortuner.jpg"
  },
  {
    "id": "car-251",
    "name": "Honda Accord",
    "type": "Hatchback",
    "capacity": 4,
    "fuelTank": 60.2,
    "transmission": "Automatic",
    "price": 325,
    "discount": 20,
    "image": "honda-accord.jpg"
  },
  {
    "id": "car-252",
    "name": "Hyundai Creta",
    "type": "Sport",
    "capacity": 8,
    "fuelTank": 76.5,
    "transmission": "Manual",
    "price": 155,
    "discount": 20,
    "image": "hyundai-creta.jpg"
  },
  {
    "id": "car-253",
    "name": "Koenigsegg",
    "type": "Sedan",
    "capacity": 5,
    "fuelTank": 46.0,
    "transmission": "Manual",
    "price": 361,
    "discount": 15,
    "image": "koenigsegg.jpg"
  },
  {
    "id": "car-254",
    "name": "Nissan GT-R",
    "type": "Sport",
    "capacity": 7,
    "fuelTank": 43.3,
    "transmission": "Manual",
    "price": 302,
    "discount": 15,
    "image": "nissan-gtr.jpg"
  },
  {
    "id": "car-255",
    "name": "Rolls-Royce",
    "type": "Sedan",
    "capacity": 4,
    "fuelTank": 69.0,
    "transmission": "Automatic",
    "price": 124,
    "discount": 20,
    "image": "rolls-royce.jpg"
  },
  {
    "id": "car-256",
    "name": "MG ZX Exclusive",
    "type": "Hatchback",
    "capacity": 3,
    "fuelTank": 73.6,
    "transmission": "Automatic",
    "price": 213,
    "discount": 0,
    "image": "mg-zx-exclusive.jpg"
  },
  {
    "id": "car-257",
    "name": "MG ZS",
    "type": "Sedan",
    "capacity": 3,
    "fuelTank": 52.7,
    "transmission": "Automatic",
    "price": 188,
    "discount": 10,
    "image": "mg-zs.jpg"
  },
  {
    "id": "car-258",
    "name": "MG Hector",
    "type": "Sedan",
    "capacity": 2,
    "fuelTank": 61.5,
    "transmission": "Manual",
    "price": 170,
    "discount": 20,
    "image": "mg-hector.jpg"
  },
  {
    "id": "car-259",
    "name": "BMW M3",
    "type": "Hatchback",
    "capacity": 4,
    "fuelTank": 58.9,
    "transmission": "Manual",
    "price": 500,
    "discount": 15,
    "image": "bmw-m3.jpg"
  },
  {
    "id": "car-260",
    "name": "Mercedes Benz",
    "type": "Sport",
    "capacity": 8,
    "fuelTank": 55.2,
    "transmission": "Automatic",
    "price": 153,
    "discount": 15,
    "image": "mercedes-benz.jpg"
  },
  {
    "id": "car-261",
    "name": "Porsche Cayenne",
    "type": "Sedan",
    "capacity": 5,
    "fuelTank": 31.6,
    "transmission": "Automatic",
    "price": 334,
    "discount": 10,
    "image": "porsche-cayenne.jpg"
  },
  {
    "id": "car-262",
    "name": "Toyota Fortuner",
    "type": "Sport",
    "capacity": 2,
    "fuelTank": 66.5,
    "transmission": "Automatic",
    "price": 100,
    "discount": 10,
    "image": "toyota-fortuner.jpg"
  },
  {
    "id": "car-263",
    "name": "Honda Accord",
    "type": "Sport",
    "capacity": 2,
    "fuelTank": 69.3,
    "transmission": "Automatic",
    "price": 66,
    "discount": 0,
    "image": "honda-accord.jpg"
  },
  {
    "id": "car-264",
    "name": "Hyundai Creta",
    "type": "Hatchback",
    "capacity": 6,
    "fuelTank": 42.2,
    "transmission": "Automatic",
    "price": 101,
    "discount": 0,
    "image": "hyundai-creta.jpg"
  },
  {
    "id": "car-265",
    "name": "Koenigsegg",
    "type": "Sport",
    "capacity": 6,
    "fuelTank": 53.1,
    "transmission": "Automatic",
    "price": 350,
    "discount": 0,
    "image": "koenigsegg.jpg"
  },
  {
    "id": "car-266",
    "name": "Nissan GT-R",
    "type": "Sport",
    "capacity": 7,
    "fuelTank": 65.9,
    "transmission": "Automatic",
    "price": 169,
    "discount": 5,
    "image": "nissan-gtr.jpg"
  },
  {
    "id": "car-267",
    "name": "Rolls-Royce",
    "type": "Hatchback",
    "capacity": 7,
    "fuelTank": 77.5,
    "transmission": "Automatic",
    "price": 275,
    "discount": 10,
    "image": "rolls-royce.jpg"
  },
  {
    "id": "car-268",
    "name": "MG ZX Exclusive",
    "type": "SUV",
    "capacity": 5,
    "fuelTank": 36.4,
    "transmission": "Manual",
    "price": 56,
    "discount": 0,
    "image": "mg-zx-exclusive.jpg"
  },
  {
    "id": "car-269",
    "name": "MG ZS",
    "type": "Hatchback",
    "capacity": 4,
    "fuelTank": 57.0,
    "transmission": "Manual",
    "price": 53,
    "discount": 0,
    "image": "mg-zs.jpg"
  },
  {
    "id": "car-270",
    "name": "MG Hector",
    "type": "Hatchback",
    "capacity": 3,
    "fuelTank": 43.7,
    "transmission": "Automatic",
    "price": 52,
    "discount": 0,
    "image": "mg-hector.jpg"
  },
  {
    "id": "car-271",
    "name": "BMW M3",
    "type": "SUV",
    "capacity": 3,
    "fuelTank": 47.3,
    "transmission": "Manual",
    "price": 172,
    "discount": 0,
    "image": "bmw-m3.jpg"
  },
  {
    "id": "car-272",
    "name": "Mercedes Benz",
    "type": "Sport",
    "capacity": 6,
    "fuelTank": 51.2,
    "transmission": "Manual",
    "price": 462,
    "discount": 0,
    "image": "mercedes-benz.jpg"
  },
  {
    "id": "car-273",
    "name": "Porsche Cayenne",
    "type": "SUV",
    "capacity": 2,
    "fuelTank": 36.8,
    "transmission": "Automatic",
    "price": 261,
    "discount": 0,
    "image": "porsche-cayenne.jpg"
  },
  {
    "id": "car-274",
    "name": "Toyota Fortuner",
    "type": "SUV",
    "capacity": 6,
    "fuelTank": 73.0,
    "transmission": "Automatic",
    "price": 315,
    "discount": 0,
    "image": "toyota-fortuner.jpg"
  },
  {
    "id": "car-275",
    "name": "Honda Accord",
    "type": "SUV",
    "capacity": 4,
    "fuelTank": 69.3,
    "transmission": "Automatic",
    "price": 308,
    "discount": 20,
    "image": "honda-accord.jpg"
  },
  {
    "id": "car-276",
    "name": "Hyundai Creta",
    "type": "Sedan",
    "capacity": 2,
    "fuelTank": 70.2,
    "transmission": "Manual",
    "price": 303,
    "discount": 0,
    "image": "hyundai-creta.jpg"
  },
  {
    "id": "car-277",
    "name": "Koenigsegg",
    "type": "Sport",
    "capacity": 6,
    "fuelTank": 38.5,
    "transmission": "Manual",
    "price": 276,
    "discount": 5,
    "image": "koenigsegg.jpg"
  },
  {
    "id": "car-278",
    "name": "Nissan GT-R",
    "type": "Sport",
    "capacity": 8,
    "fuelTank": 45.6,
    "transmission": "Manual",
    "price": 325,
    "discount": 15,
    "image": "nissan-gtr.jpg"
  },
  {
    "id": "car-279",
    "name": "Rolls-Royce",
    "type": "Sport",
    "capacity": 2,
    "fuelTank": 42.0,
    "transmission": "Manual",
    "price": 136,
    "discount": 15,
    "image": "rolls-royce.jpg"
  },
  {
    "id": "car-280",
    "name": "MG ZX Exclusive",
    "type": "SUV",
    "capacity": 4,
    "fuelTank": 50.7,
    "transmission": "Automatic",
    "price": 349,
    "discount": 15,
    "image": "mg-zx-exclusive.jpg"
  },
  {
    "id": "car-281",
    "name": "MG ZS",
    "type": "Sedan",
    "capacity": 3,
    "fuelTank": 52.6,
    "transmission": "Manual",
    "price": 366,
    "discount": 0,
    "image": "mg-zs.jpg"
  },
  {
    "id": "car-282",
    "name": "MG Hector",
    "type": "Sedan",
    "capacity": 2,
    "fuelTank": 43.4,
    "transmission": "Manual",
    "price": 318,
    "discount": 5,
    "image": "mg-hector.jpg"
  },
  {
    "id": "car-283",
    "name": "BMW M3",
    "type": "Sedan",
    "capacity": 5,
    "fuelTank": 50.1,
    "transmission": "Automatic",
    "price": 329,
    "discount": 10,
    "image": "bmw-m3.jpg"
  },
  {
    "id": "car-284",
    "name": "Mercedes Benz",
    "type": "SUV",
    "capacity": 8,
    "fuelTank": 54.4,
    "transmission": "Manual",
    "price": 432,
    "discount": 5,
    "image": "mercedes-benz.jpg"
  },
  {
    "id": "car-285",
    "name": "Porsche Cayenne",
    "type": "Sedan",
    "capacity": 2,
    "fuelTank": 49.8,
    "transmission": "Manual",
    "price": 476,
    "discount": 10,
    "image": "porsche-cayenne.jpg"
  },
  {
    "id": "car-286",
    "name": "Toyota Fortuner",
    "type": "SUV",
    "capacity": 5,
    "fuelTank": 43.5,
    "transmission": "Manual",
    "price": 482,
    "discount": 5,
    "image": "toyota-fortuner.jpg"
  },
  {
    "id": "car-287",
    "name": "Honda Accord",
    "type": "Sedan",
    "capacity": 5,
    "fuelTank": 72.6,
    "transmission": "Automatic",
    "price": 289,
    "discount": 0,
    "image": "honda-accord.jpg"
  },
  {
    "id": "car-288",
    "name": "Hyundai Creta",
    "type": "Hatchback",
    "capacity": 6,
    "fuelTank": 55.3,
    "transmission": "Automatic",
    "price": 407,
    "discount": 5,
    "image": "hyundai-creta.jpg"
  },
  {
    "id": "car-289",
    "name": "Koenigsegg",
    "type": "SUV",
    "capacity": 8,
    "fuelTank": 39.8,
    "transmission": "Automatic",
    "price": 326,
    "discount": 20,
    "image": "koenigsegg.jpg"
  },
  {
    "id": "car-290",
    "name": "Nissan GT-R",
    "type": "Sedan",
    "capacity": 7,
    "fuelTank": 34.3,
    "transmission": "Automatic",
    "price": 364,
    "discount": 0,
    "image": "nissan-gtr.jpg"
  },
  {
    "id": "car-291",
    "name": "Rolls-Royce",
    "type": "Hatchback",
    "capacity": 5,
    "fuelTank": 65.9,
    "transmission": "Automatic",
    "price": 206,
    "discount": 15,
    "image": "rolls-royce.jpg"
  },
  {
    "id": "car-292",
    "name": "MG ZX Exclusive",
    "type": "SUV",
    "capacity": 4,
    "fuelTank": 66.8,
    "transmission": "Manual",
    "price": 377,
    "discount": 0,
    "image": "mg-zx-exclusive.jpg"
  },
  {
    "id": "car-293",
    "name": "MG ZS",
    "type": "Hatchback",
    "capacity": 4,
    "fuelTank": 69.8,
    "transmission": "Manual",
    "price": 367,
    "discount": 15,
    "image": "mg-zs.jpg"
  },
  {
    "id": "car-294",
    "name": "MG Hector",
    "type": "SUV",
    "capacity": 5,
    "fuelTank": 66.0,
    "transmission": "Automatic",
    "price": 168,
    "discount": 10,
    "image": "mg-hector.jpg"
  },
  {
    "id": "car-295",
    "name": "BMW M3",
    "type": "Hatchback",
    "capacity": 8,
    "fuelTank": 68.3,
    "transmission": "Manual",
    "price": 250,
    "discount": 20,
    "image": "bmw-m3.jpg"
  },
  {
    "id": "car-296",
    "name": "Mercedes Benz",
    "type": "Hatchback",
    "capacity": 2,
    "fuelTank": 80.0,
    "transmission": "Manual",
    "price": 274,
    "discount": 10,
    "image": "mercedes-benz.jpg"
  },
  {
    "id": "car-297",
    "name": "Porsche Cayenne",
    "type": "Sedan",
    "capacity": 2,
    "fuelTank": 75.0,
    "transmission": "Automatic",
    "price": 72,
    "discount": 5,
    "image": "porsche-cayenne.jpg"
  },
  {
    "id": "car-298",
    "name": "Toyota Fortuner",
    "type": "Hatchback",
    "capacity": 2,
    "fuelTank": 38.5,
    "transmission": "Manual",
    "price": 381,
    "discount": 0,
    "image": "toyota-fortuner.jpg"
  },
  {
    "id": "car-299",
    "name": "Honda Accord",
    "type": "Hatchback",
    "capacity": 5,
    "fuelTank": 48.6,
    "transmission": "Manual",
    "price": 86,
    "discount": 20,
    "image": "honda-accord.jpg"
  },
  {
    "id": "car-300",
    "name": "Hyundai Creta",
    "type": "Sport",
    "capacity": 3,
    "fuelTank": 64.6,
    "transmission": "Automatic",
    "price": 463,
    "discount": 10,
    "image": "hyundai-creta.jpg"
  }
];